CREATE DATABASE IF NOT EXISTS WarehouseDB
    DEFAULT CHARACTER SET utf8
	DEFAULT COLLATE utf8_general_ci;

USE WarehouseDB;

CREATE TABLE Users(
    UserID INT PRIMARY KEY AUTO_INCREMENT,
    Username NVARCHAR(255) UNIQUE NOT NULL,
    Password NVARCHAR(255) NOT NULL,
    PriviligeLevel NVARCHAR(6) DEFAULT 'user'
);

CREATE TABLE Logs(
    LogID INT PRIMARY KEY AUTO_INCREMENT,
    Action NVARCHAR(50) NOT NULL,
    Time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UserID INT NOT NULL,
    FOREIGN KEY(UserID) REFERENCES Users(UserID)
);

CREATE TABLE Products(
    ProductID INT PRIMARY KEY AUTO_INCREMENT,
    ItemNumber NVARCHAR(10) UNIQUE NOT NULL,
    Category NVARCHAR(255),
    ProductName NVARCHAR(255) NOT NULL,
    NetPrice DECIMAL(12,3) NOT NULL,
    GrossPrice DECIMAL(12,3)
);

CREATE TABLE Warehouses(
    WarehouseID INT PRIMARY KEY AUTO_INCREMENT,
    WarehouseName NVARCHAR(255) UNIQUE NOT NULL,
    AdditionalDetails NVARCHAR(255)
);

CREATE TABLE Stocks(
    WarehouseID INT NOT NULL,
    ProductID INT NOT NULL,
    Amount INT UNSIGNED,
    FOREIGN KEY(ProductID) REFERENCES Products(ProductID),
    FOREIGN KEY(WarehouseID) REFERENCES Warehouses(WarehouseID)
);